### ISSUE TITLE
Is any particular version of CUDA required? "torch.cuda.is_available() is False"

### ISSUE THREAD

**Issue by ValkerN** [ai-forever/Kandinsky-2#34]
On startup, it doesn't seem to see the CUDA system install. With projects in other environments, everything works fine on it. Is any particular version of CUDA required?

The system (Win 11) has the latest version of CUDA 12.1 installed. Kandinsky2 installed in a new environment:
```
conda:
  - python=3.10.10
pip:
  - opencv-python
  - git+https://github.com/openai/CLIP.git
  - git+https://github.com/ai-forever/Kandinsky-2.git
```

In response to:
```
from kandinsky2 import get_kandinsky2
model = get_kandinsky2('cuda', task_type='text2img', model_version='2.1', use_flash_attention=False)
```
Throws an error:
> Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by FurkanGozukara** [comment]
I made a tutorial and it worked very well for me

```
C:\Users\King\Videos>python test.py
PyTorch version: 1.13.1+cu117
CUDA version: 11.7
cuDNN version: 8500

C:\Users\King\Videos>
```

```
import torch

def main():
    print("PyTorch version: {}".format(torch.__version__))
    print("CUDA version: {}".format(torch.version.cuda))
    print("cuDNN version: {}".format(torch.backends.cudnn.version()))

if __name__ == "__main__":
    main()
```



Thanks I also made a tutorial video

27.) Python Script - Jupyter Based - PC - Free
[**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU)
[![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png)
](https://youtu.be/dYt9xJ7dnpU)

**Comment by wedigitalize** [comment]
> I made a tutorial and it worked very well for me
> 
> ```
> C:\Users\King\Videos>python test.py
> PyTorch version: 1.13.1+cu117
> CUDA version: 11.7
> cuDNN version: 8500
> 
> C:\Users\King\Videos>
> ```
> 
> ```
> import torch
> 
> def main():
>     print("PyTorch version: {}".format(torch.__version__))
>     print("CUDA version: {}".format(torch.version.cuda))
>     print("cuDNN version: {}".format(torch.backends.cudnn.version()))
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> 27.) Python Script - Jupyter Based - PC - Free [**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU) [![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png) ](https://youtu.be/dYt9xJ7dnpU)

**Sir, I am your subscriber. I am getting the same error. I have installed CUDA 12.1, 11.7 and 11.8. i am getting the below error just like [ValkerN](https://github.com/ValkerN)**


model = get_kandinsky2(
    'cuda', 
    task_type='text2img', 
    cache_dir='/tmp/kandinsky2', 
    model_version='2.1', 
    use_flash_attention=False
)
C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:637: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\nesamani\AppData\Local\Temp\ipykernel_17104\1681258332.py:1 in <module>                    │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ 'C:\\Users\\nesamani\\AppData\\Local\\Temp\\ipykernel_17104\\1681258332.py'                         │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\__init__.py: │
│ 179 in get_kandinsky2                                                                            │
│                                                                                                  │
│   176 │   │   │   use_auth_token=use_auth_token,                                                 │
│   177 │   │   )                                                                                  │
│   178 │   elif model_version == "2.1":                                                           │
│ ❱ 179 │   │   model = get_kandinsky2_1(                                                          │
│   180 │   │   │   device,                                                                        │
│   181 │   │   │   task_type=task_type,                                                           │
│   182 │   │   │   cache_dir=cache_dir,                                                           │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\__init__.py: │
│ 159 in get_kandinsky2_1                                                                          │
│                                                                                                  │
│   156 │   config["image_enc_params"]["ckpt_path"] = os.path.join(cache_dir, "movq_final.ckpt")   │
│   157 │   cache_model_name = os.path.join(cache_dir, model_name)                                 │
│   158 │   cache_prior_name = os.path.join(cache_dir, prior_name)                                 │
│ ❱ 159 │   model = Kandinsky2_1(config, cache_model_name, cache_prior_name, device, task_type=t   │
│   160 │   return model                                                                           │
│   161                                                                                            │
│   162                                                                                            │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\kandinsky2_1 │
│ _model.py:57 in __init__                                                                         │
│                                                                                                  │
│    54 │   │   │   clip_mean,                                                                     │
│    55 │   │   │   clip_std,                                                                      │
│    56 │   │   )                                                                                  │
│ ❱  57 │   │   self.prior.load_state_dict(torch.load(prior_path), strict=False)                   │
│    58 │   │   if self.use_fp16:                                                                  │
│    59 │   │   │   self.prior = self.prior.half()                                                 │
│    60 │   │   self.text_encoder = TextEncoder(**self.config["text_enc_params"])                  │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 809 in load                                                                                      │
│                                                                                                  │
│    806 │   │   │   │   │   │   return _load(opened_zipfile, map_location, _weights_only_unpickl  │
│    807 │   │   │   │   │   except RuntimeError as e:                                             │
│    808 │   │   │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None   │
│ ❱  809 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module, **pickle_load_  │
│    810 │   │   if weights_only:                                                                  │
│    811 │   │   │   try:                                                                          │
│    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1172 in _load                                                                                    │
│                                                                                                  │
│   1169 │                                                                                         │
│   1170 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                           │
│   1171 │   unpickler.persistent_load = persistent_load                                           │
│ ❱ 1172 │   result = unpickler.load()                                                             │
│   1173 │                                                                                         │
│   1174 │   torch._utils._validate_loaded_sparse_tensors()                                        │
│   1175                                                                                           │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\pickle.py:1213 in load                │
│                                                                                                  │
│   1210 │   │   │   │   if not key:                                                               │
│   1211 │   │   │   │   │   raise EOFError                                                        │
│   1212 │   │   │   │   assert isinstance(key, bytes_types)                                       │
│ ❱ 1213 │   │   │   │   dispatch[key[0]](self)                                                    │
│   1214 │   │   except _Stop as stopinst:                                                         │
│   1215 │   │   │   return stopinst.value                                                         │
│   1216                                                                                           │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\pickle.py:1254 in load_binpersid      │
│                                                                                                  │
│   1251 │                                                                                         │
│   1252 │   def load_binpersid(self):                                                             │
│   1253 │   │   pid = self.stack.pop()                                                            │
│ ❱ 1254 │   │   self.append(self.persistent_load(pid))                                            │
│   1255 │   dispatch[BINPERSID[0]] = load_binpersid                                               │
│   1256 │                                                                                         │
│   1257 │   def load_none(self):                                                                  │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1142 in persistent_load                                                                          │
│                                                                                                  │
│   1139 │   │   │   typed_storage = loaded_storages[key]                                          │
│   1140 │   │   else:                                                                             │
│   1141 │   │   │   nbytes = numel * torch._utils._element_size(dtype)                            │
│ ❱ 1142 │   │   │   typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location  │
│   1143 │   │                                                                                     │
│   1144 │   │   return typed_storage                                                              │
│   1145                                                                                           │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1116 in load_tensor                                                                              │
│                                                                                                  │
│   1113 │   │   # TODO: Once we decide to break serialization FC, we can                          │
│   1114 │   │   # stop wrapping with TypedStorage                                                 │
│   1115 │   │   typed_storage = torch.storage.TypedStorage(                                       │
│ ❱ 1116 │   │   │   wrap_storage=restore_location(storage, location),                             │
│   1117 │   │   │   dtype=dtype,                                                                  │
│   1118 │   │   │   _internal=True)                                                               │
│   1119                                                                                           │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 217 in default_restore_location                                                                  │
│                                                                                                  │
│    214                                                                                           │
│    215 def default_restore_location(storage, location):                                          │
│    216 │   for _, _, fn in _package_registry:                                                    │
│ ❱  217 │   │   result = fn(storage, location)                                                    │
│    218 │   │   if result is not None:                                                            │
│    219 │   │   │   return result                                                                 │
│    220 │   raise RuntimeError("don't know how to restore data location of "                      │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 182 in _cuda_deserialize                                                                         │
│                                                                                                  │
│    179                                                                                           │
│    180 def _cuda_deserialize(obj, location):                                                     │
│    181 │   if location.startswith('cuda'):                                                       │
│ ❱  182 │   │   device = validate_cuda_device(location)                                           │
│    183 │   │   if getattr(obj, "_torch_load_uninitialized", False):                              │
│    184 │   │   │   with torch.cuda.device(device):                                               │
│    185 │   │   │   │   return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))  │
│                                                                                                  │
│ C:\Users\nesamani\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 166 in validate_cuda_device                                                                      │
│                                                                                                  │
│    163 │   device = torch.cuda._utils._get_device_index(location, True)                          │
│    164 │                                                                                         │
│    165 │   if not torch.cuda.is_available():                                                     │
│ ❱  166 │   │   raise RuntimeError('Attempting to deserialize object on a CUDA '                  │
│    167 │   │   │   │   │   │      'device but torch.cuda.is_available() is False. '              │
│    168 │   │   │   │   │   │      'If you are running on a CPU-only machine, '                   │
│    169 │   │   │   │   │   │      'please use torch.load with map_location=torch.device(\'cpu\'  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are 
running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to 
the CPU.

**Comment by Blucknote** [comment]
I have exactly same versions as FurkanGozukara , but in WSL.
You may find https://pytorch.org/get-started/locally/ usefull

**Comment by wedigitalize** [comment]
> I made a tutorial and it worked very well for me
> 
> ```
> C:\Users\King\Videos>python test.py
> PyTorch version: 1.13.1+cu117
> CUDA version: 11.7
> cuDNN version: 8500
> 
> C:\Users\King\Videos>
> ```
> 
> ```
> import torch
> 
> def main():
>     print("PyTorch version: {}".format(torch.__version__))
>     print("CUDA version: {}".format(torch.version.cuda))
>     print("cuDNN version: {}".format(torch.backends.cudnn.version()))
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> 27.) Python Script - Jupyter Based - PC - Free [**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU) [![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png) ](https://youtu.be/dYt9xJ7dnpU)

**Dear sir, I am your subscriber (with all my 4 accounts). It would be helpful if you can help me fix the issue?**

C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\huggingface_hub\file_download.py:637: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Users\obsig\AppData\Local\Temp\ipykernel_8020\1681258332.py:1 in <module>                     │
│                                                                                                  │
│ [Errno 2] No such file or directory:                                                             │
│ 'C:\\Users\\obsig\\AppData\\Local\\Temp\\ipykernel_8020\\1681258332.py'                          │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\__init__.py: │
│ 179 in get_kandinsky2                                                                            │
│                                                                                                  │
│   176 │   │   │   use_auth_token=use_auth_token,                                                 │
│   177 │   │   )                                                                                  │
│   178 │   elif model_version == "2.1":                                                           │
│ ❱ 179 │   │   model = get_kandinsky2_1(                                                          │
│   180 │   │   │   device,                                                                        │
│   181 │   │   │   task_type=task_type,                                                           │
│   182 │   │   │   cache_dir=cache_dir,                                                           │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\__init__.py: │
│ 159 in get_kandinsky2_1                                                                          │
│                                                                                                  │
│   156 │   config["image_enc_params"]["ckpt_path"] = os.path.join(cache_dir, "movq_final.ckpt")   │
│   157 │   cache_model_name = os.path.join(cache_dir, model_name)                                 │
│   158 │   cache_prior_name = os.path.join(cache_dir, prior_name)                                 │
│ ❱ 159 │   model = Kandinsky2_1(config, cache_model_name, cache_prior_name, device, task_type=t   │
│   160 │   return model                                                                           │
│   161                                                                                            │
│   162                                                                                            │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\kandinsky2\kandinsky2_1 │
│ _model.py:57 in __init__                                                                         │
│                                                                                                  │
│    54 │   │   │   clip_mean,                                                                     │
│    55 │   │   │   clip_std,                                                                      │
│    56 │   │   )                                                                                  │
│ ❱  57 │   │   self.prior.load_state_dict(torch.load(prior_path), strict=False)                   │
│    58 │   │   if self.use_fp16:                                                                  │
│    59 │   │   │   self.prior = self.prior.half()                                                 │
│    60 │   │   self.text_encoder = TextEncoder(**self.config["text_enc_params"])                  │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 809 in load                                                                                      │
│                                                                                                  │
│    806 │   │   │   │   │   │   return _load(opened_zipfile, map_location, _weights_only_unpickl  │
│    807 │   │   │   │   │   except RuntimeError as e:                                             │
│    808 │   │   │   │   │   │   raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None   │
│ ❱  809 │   │   │   │   return _load(opened_zipfile, map_location, pickle_module, **pickle_load_  │
│    810 │   │   if weights_only:                                                                  │
│    811 │   │   │   try:                                                                          │
│    812 │   │   │   │   return _legacy_load(opened_file, map_location, _weights_only_unpickler,   │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1172 in _load                                                                                    │
│                                                                                                  │
│   1169 │                                                                                         │
│   1170 │   unpickler = UnpicklerWrapper(data_file, **pickle_load_args)                           │
│   1171 │   unpickler.persistent_load = persistent_load                                           │
│ ❱ 1172 │   result = unpickler.load()                                                             │
│   1173 │                                                                                         │
│   1174 │   torch._utils._validate_loaded_sparse_tensors()                                        │
│   1175                                                                                           │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\pickle.py:1213 in load                │
│                                                                                                  │
│   1210 │   │   │   │   if not key:                                                               │
│   1211 │   │   │   │   │   raise EOFError                                                        │
│   1212 │   │   │   │   assert isinstance(key, bytes_types)                                       │
│ ❱ 1213 │   │   │   │   dispatch[key[0]](self)                                                    │
│   1214 │   │   except _Stop as stopinst:                                                         │
│   1215 │   │   │   return stopinst.value                                                         │
│   1216                                                                                           │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\pickle.py:1254 in load_binpersid      │
│                                                                                                  │
│   1251 │                                                                                         │
│   1252 │   def load_binpersid(self):                                                             │
│   1253 │   │   pid = self.stack.pop()                                                            │
│ ❱ 1254 │   │   self.append(self.persistent_load(pid))                                            │
│   1255 │   dispatch[BINPERSID[0]] = load_binpersid                                               │
│   1256 │                                                                                         │
│   1257 │   def load_none(self):                                                                  │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1142 in persistent_load                                                                          │
│                                                                                                  │
│   1139 │   │   │   typed_storage = loaded_storages[key]                                          │
│   1140 │   │   else:                                                                             │
│   1141 │   │   │   nbytes = numel * torch._utils._element_size(dtype)                            │
│ ❱ 1142 │   │   │   typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location  │
│   1143 │   │                                                                                     │
│   1144 │   │   return typed_storage                                                              │
│   1145                                                                                           │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 1116 in load_tensor                                                                              │
│                                                                                                  │
│   1113 │   │   # TODO: Once we decide to break serialization FC, we can                          │
│   1114 │   │   # stop wrapping with TypedStorage                                                 │
│   1115 │   │   typed_storage = torch.storage.TypedStorage(                                       │
│ ❱ 1116 │   │   │   wrap_storage=restore_location(storage, location),                             │
│   1117 │   │   │   dtype=dtype,                                                                  │
│   1118 │   │   │   _internal=True)                                                               │
│   1119                                                                                           │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 217 in default_restore_location                                                                  │
│                                                                                                  │
│    214                                                                                           │
│    215 def default_restore_location(storage, location):                                          │
│    216 │   for _, _, fn in _package_registry:                                                    │
│ ❱  217 │   │   result = fn(storage, location)                                                    │
│    218 │   │   if result is not None:                                                            │
│    219 │   │   │   return result                                                                 │
│    220 │   raise RuntimeError("don't know how to restore data location of "                      │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 182 in _cuda_deserialize                                                                         │
│                                                                                                  │
│    179                                                                                           │
│    180 def _cuda_deserialize(obj, location):                                                     │
│    181 │   if location.startswith('cuda'):                                                       │
│ ❱  182 │   │   device = validate_cuda_device(location)                                           │
│    183 │   │   if getattr(obj, "_torch_load_uninitialized", False):                              │
│    184 │   │   │   with torch.cuda.device(device):                                               │
│    185 │   │   │   │   return torch.UntypedStorage(obj.nbytes(), device=torch.device(location))  │
│                                                                                                  │
│ C:\Users\obsig\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py: │
│ 166 in validate_cuda_device                                                                      │
│                                                                                                  │
│    163 │   device = torch.cuda._utils._get_device_index(location, True)                          │
│    164 │                                                                                         │
│    165 │   if not torch.cuda.is_available():                                                     │
│ ❱  166 │   │   raise RuntimeError('Attempting to deserialize object on a CUDA '                  │
│    167 │   │   │   │   │   │      'device but torch.cuda.is_available() is False. '              │
│    168 │   │   │   │   │   │      'If you are running on a CPU-only machine, '                   │
│    169 │   │   │   │   │   │      'please use torch.load with map_location=torch.device(\'cpu\'  │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are 
running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to 
the CPU.

C:\Windows\System32>pip show torch
Name: torch
Version: 1.13.1+cu117
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: c:\users\obsig\appdata\local\programs\python\python310\lib\site-packages
Requires: typing-extensions
Required-by: accelerate, asteroid-filterbanks, clip, fairscale, julius, kandinsky2, openai-whisper, peft, pytorch-lightning, pytorch-metric-learning, speechbrain, torch-audiomentations, torch-pitch-shift, torchaudio, torchmetrics, torchvision, xformers

C:\Windows\System32>nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_19:00:59_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0

What's could be the issue?

**Comment by FurkanGozukara** [comment]
@wedigitalize @Blucknote

Both errors looking like it can't find installed python file. Also you both have installed python into users directory. Could you uninstall and install python directly into c drive? I wonder if it would fix issue

**Comment by wedigitalize** [comment]
> I made a tutorial and it worked very well for me
> 
> ```
> C:\Users\King\Videos>python test.py
> PyTorch version: 1.13.1+cu117
> CUDA version: 11.7
> cuDNN version: 8500
> 
> C:\Users\King\Videos>
> ```
> 
> ```
> import torch
> 
> def main():
>     print("PyTorch version: {}".format(torch.__version__))
>     print("CUDA version: {}".format(torch.version.cuda))
>     print("cuDNN version: {}".format(torch.backends.cudnn.version()))
> 
> if __name__ == "__main__":
>     main()
> ```
> 
> 27.) Python Script - Jupyter Based - PC - Free [**Midjourney Level NEW Open Source Kandinsky 2.1 Beats Stable Diffusion - Installation And Usage Guide**](https://youtu.be/dYt9xJ7dnpU) [![image](https://user-images.githubusercontent.com/19240467/230183162-8a6f7e84-dcd9-45b5-a94c-b93a10778f42.png) ](https://youtu.be/dYt9xJ7dnpU)

pip install opencv-python


> @wedigitalize Error is looking like both file found error and torch Cuda error very interesting. You have installed python into users directory. Could you uninstall and install python directly into c drive? I wonder if it would fix issue
> 
> Also did you restart computer and tried again? It fixed error for someone on my youtube video

Dear sir,
I have restarted several times. I have been trying to fix this from yesterday. I have watched the videos so many times. followed it step by step. This is the error that i am unable to fix.

__


model = get_kandinsky2(
    'cuda', 
    task_type='text2img', 
    cache_dir='/tmp/kandinsky2', 
    model_version='2.1', 
    use_flash_attention=False
)

C:\Python310\lib\site-packages\huggingface_hub\file_download.py:637: FutureWarning: `cached_download` is the legacy way to download files from the HF hub, please consider upgrading to `hf_hub_download`
  warnings.warn(
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[4], line 1
----> 1 model = get_kandinsky2(
      2     'cuda', 
      3     task_type='text2img', 
      4     cache_dir='/tmp/kandinsky2', 
      5     model_version='2.1', 
      6     use_flash_attention=False
      7 )

File C:\Python310\lib\site-packages\kandinsky2\__init__.py:179, in get_kandinsky2(device, task_type, cache_dir, use_auth_token, model_version, use_flash_attention)
    172     model = get_kandinsky2_0(
    173         device,
    174         task_type=task_type,
    175         cache_dir=cache_dir,
    176         use_auth_token=use_auth_token,
    177     )
    178 elif model_version == "2.1":
--> 179     model = get_kandinsky2_1(
    180         device,
    181         task_type=task_type,
    182         cache_dir=cache_dir,
    183         use_auth_token=use_auth_token,
    184         use_flash_attention=use_flash_attention,
    185     )
    186 else:
    187     raise ValueError("Only 2.0 and 2.1 is available")

File C:\Python310\lib\site-packages\kandinsky2\__init__.py:159, in get_kandinsky2_1(device, task_type, cache_dir, use_auth_token, use_flash_attention)
    157 cache_model_name = os.path.join(cache_dir, model_name)
    158 cache_prior_name = os.path.join(cache_dir, prior_name)
--> 159 model = Kandinsky2_1(config, cache_model_name, cache_prior_name, device, task_type=task_type)
    160 return model

File C:\Python310\lib\site-packages\kandinsky2\kandinsky2_1_model.py:57, in Kandinsky2_1.__init__(self, config, model_path, prior_path, device, task_type)
     47 clip_mean, clip_std = torch.load(
     48     config["prior"]["clip_mean_std_path"], map_location="cpu"
     49 )
     51 self.prior = PriorDiffusionModel(
     52     config["prior"]["params"],
     53     self.tokenizer2,
     54     clip_mean,
     55     clip_std,
     56 )
---> 57 self.prior.load_state_dict(torch.load(prior_path), strict=False)
     58 if self.use_fp16:
     59     self.prior = self.prior.half()

File C:\Python310\lib\site-packages\torch\serialization.py:809, in load(f, map_location, pickle_module, weights_only, **pickle_load_args)
    807             except RuntimeError as e:
    808                 raise pickle.UnpicklingError(UNSAFE_MESSAGE + str(e)) from None
--> 809         return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
    810 if weights_only:
    811     try:

File C:\Python310\lib\site-packages\torch\serialization.py:1172, in _load(zip_file, map_location, pickle_module, pickle_file, **pickle_load_args)
   1170 unpickler = UnpicklerWrapper(data_file, **pickle_load_args)
   1171 unpickler.persistent_load = persistent_load
-> 1172 result = unpickler.load()
   1174 torch._utils._validate_loaded_sparse_tensors()
   1176 return result

File C:\Python310\lib\pickle.py:1213, in _Unpickler.load(self)
   1211             raise EOFError
   1212         assert isinstance(key, bytes_types)
-> 1213         dispatch[key[0]](self)
   1214 except _Stop as stopinst:
   1215     return stopinst.value

File C:\Python310\lib\pickle.py:1254, in _Unpickler.load_binpersid(self)
   1252 def load_binpersid(self):
   1253     pid = self.stack.pop()
-> 1254     self.append(self.persistent_load(pid))

File C:\Python310\lib\site-packages\torch\serialization.py:1142, in _load.<locals>.persistent_load(saved_id)
   1140 else:
   1141     nbytes = numel * torch._utils._element_size(dtype)
-> 1142     typed_storage = load_tensor(dtype, nbytes, key, _maybe_decode_ascii(location))
   1144 return typed_storage

File C:\Python310\lib\site-packages\torch\serialization.py:1116, in _load.<locals>.load_tensor(dtype, numel, key, location)
   1112 storage = zip_file.get_storage_from_record(name, numel, torch.UntypedStorage)._typed_storage()._untyped_storage
   1113 # TODO: Once we decide to break serialization FC, we can
   1114 # stop wrapping with TypedStorage
   1115 typed_storage = torch.storage.TypedStorage(
-> 1116     wrap_storage=restore_location(storage, location),
   1117     dtype=dtype,
   1118     _internal=True)
   1120 if typed_storage._data_ptr() != 0:
   1121     loaded_storages[key] = typed_storage

File C:\Python310\lib\site-packages\torch\serialization.py:217, in default_restore_location(storage, location)
    215 def default_restore_location(storage, location):
    216     for _, _, fn in _package_registry:
--> 217         result = fn(storage, location)
    218         if result is not None:
    219             return result

File C:\Python310\lib\site-packages\torch\serialization.py:182, in _cuda_deserialize(obj, location)
    180 def _cuda_deserialize(obj, location):
    181     if location.startswith('cuda'):
--> 182         device = validate_cuda_device(location)
    183         if getattr(obj, "_torch_load_uninitialized", False):
    184             with torch.cuda.device(device):

File C:\Python310\lib\site-packages\torch\serialization.py:166, in validate_cuda_device(location)
    163 device = torch.cuda._utils._get_device_index(location, True)
    165 if not torch.cuda.is_available():
--> 166     raise RuntimeError('Attempting to deserialize object on a CUDA '
    167                        'device but torch.cuda.is_available() is False. '
    168                        'If you are running on a CPU-only machine, '
    169                        'please use torch.load with map_location=torch.device(\'cpu\') '
    170                        'to map your storages to the CPU.')
    171 device_count = torch.cuda.device_count()
    172 if device >= device_count:

RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

**Comment by FurkanGozukara** [comment]
@wedigitalize can you run the attached python file?

open cmd and run it as 

python test.py

and what do you see?

[test.zip](https://github.com/ai-forever/Kandinsky-2/files/11170824/test.zip)

it is this code

import torch

```
def main():
    print("PyTorch version: {}".format(torch.__version__))
    print("CUDA version: {}".format(torch.version.cuda))
    print("cuDNN version: {}".format(torch.backends.cudnn.version()))

if __name__ == "__main__":
    main()
```

**Comment by wedigitalize** [comment]
> @wedigitalize can you run the attached python file?
> 
> open cmd and run it as
> 
> python test.py
> 
> and what do you see?
> 
> [test.zip](https://github.com/ai-forever/Kandinsky-2/files/11170824/test.zip)
> 
> it is this code
> 
> import torch
> 
> ```
> def main():
>     print("PyTorch version: {}".format(torch.__version__))
>     print("CUDA version: {}".format(torch.version.cuda))
>     print("cuDNN version: {}".format(torch.backends.cudnn.version()))
> 
> if __name__ == "__main__":
>     main()
> ```

**I changed the python's installation directory and I down graded the torch version. It worked**
🙏🏿🙏🏿🙏🏿Thankyou very much Dr [FurkanGozukara](https://github.com/FurkanGozukara)🙏🏿🙏🏿🙏🏿
![image](https://user-images.githubusercontent.com/110510874/230393966-6845bd6c-7981-41a1-9ec8-3c6c47f68682.png)

**Comment by halr9000** [comment]
> On startup, it doesn't seem to see the CUDA system install. With projects in other environments, everything works fine on it. Is any particular version of CUDA required?
> 
> The system (Win 11) has the latest version of CUDA 12.1 installed. Kandinsky2 installed in a new environment:

>   - opencv-python

Yup this came up in #5 .

> Throws an error:
>> Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.

I was able to get past this by adding an extra torch install step before pip install <kadinsky> like so:

`pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`

Which worked great, but I would actually like the whole thing to work on Windows out of the box after cloning. I'm trying to figure out how to "do it right", and where I'm stuck is figuring out why [this ](https://github.com/ai-forever/Kandinsky-2/blob/main/setup.py#L13 )doesn't seem to install torch-with-cuda compiled in. Any ideas?

**Comment by halr9000** [comment]
> > I was able to get past this by adding an extra torch install step before `pip install [this repo]` like so:
> > `pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`
> 
> Yes, it worked, thanks!
> 
> The problem, however, is not to duplicate the system installation of CUDA (because it all takes up a lot of disk space). But, as I understand it, this is a question for Pytorch installation (why does it not see the system installation if installed without the built-in CUDA package).
> 
> Indeed, it would be nice to add instructions for a complete installation to this repository.

Way I understand it, this only installs a new copy of torch -- not Cuda. But you can do that safely in venv/conda, that's what they are for. But Cuda isn't python, it's native win32/C stuff.
